groups:
  - name: 'TRANSCENDENCE'
    rules:
      # for General instance
      - alert: InstanceDown
        expr: up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Instance {{ $labels.instance }} down"
          description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 1 minute."

      # for cAdvisor
      - alert: HighContainerCPUUsage
        expr: (sum(rate(container_cpu_usage_seconds_total{name!=""}[3m])) BY (instance, name) * 100) > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage in container {{ $labels.name }}"
          description: "Container {{ $labels.name }} is using more than 80% CPU."

      - alert: HighContainerMemoryUsage
        expr: (sum(container_memory_usage_bytes{name!=""}) BY (instance, name)) > 2000000000
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage in container {{ $labels.name }}"
          description: "Container {{ $labels.name }} is using more than 2GB of memory."

      # for Django
      - alert: High5xxResponses
        expr: rate(django_http_responses_total_by_status_total{job="django", status=~"5.."}[5m]) > 1
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "High number of 5xx responses from Django server"
          description: "The Django server is returning a high number of 5xx responses."

      - alert: HighRequestLatency
        expr: histogram_quantile(0.95, sum(irate(django_http_requests_latency_seconds_by_view_method_bucket{job="django"}[5m])) by (le)) > 0.5
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High request latency from Django server"
          description: "The Django server is experiencing high request latency."

      # for Nginx
      - alert: NginxDown
        expr: nginx_up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Nginx instance is down"
          description: "Nginx has been down for more than 1 minute"

      - alert: NginxHighErrorRate
        expr: rate(nginx_http_requests_total{status=~"^5.*"}[5m]) / rate(nginx_http_requests_total[5m]) * 100 > 5
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High error rate"
          description: "More than 5% of requests are resulting in 5xx errors"

      - alert: NginxLatencyHigh
        expr: rate(nginx_connections_waiting[5m]) > rate(nginx_connections_active[5m]) * 0.5
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High latency detected"
          description: "More than 50% of connections are in waiting state"

      # for Node alerts
      - alert: HighCPUUsage
        expr: 100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage detected"
          description: "CPU usage is above 80% for 5 minutes"

      - alert: HighMemoryUsage
        expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100 > 85
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage detected"
          description: "Memory usage is above 85%"

      - alert: DiskSpaceRunningOut
        expr: (node_filesystem_size_bytes{mountpoint="/"} - node_filesystem_free_bytes{mountpoint="/"}) / node_filesystem_size_bytes{mountpoint="/"} * 100 > 85
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Disk space running low"
          description: "Disk usage is above 85%"

      # PostgreSQL Alerts
      - alert: PostgresqlDown
        expr: pg_up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "PostgreSQL instance {{ $labels.instance }} is down"
          description: "PostgreSQL instance has been down for more than 1 minute"

      - alert: HighPostgresConnections
        expr: pg_stat_activity_count{state="active"} > 100
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High number of active PostgreSQL connections on {{ $labels.instance }}"
          description: "PostgreSQL instance {{ $labels.instance }} has more than 100 active connections."


  - name: Test alert
    rules:
      - alert: TestAlert
        expr: vector(1)  # this will always trigger
        for: 10s
        labels:
          severity: warning
        annotations:
          summary: "Test alert"
          description: "This is a test alert to verify email notifications"
