# global:
#   scrape_interval: 15s

# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets:
#             - 'alertmanager:9093'

# rule_files:
#   - './rules/alerts.yml'

# scrape_configs:
#   - job_name: 'cadvisor'
#     static_configs:
#       - targets: ['cadvisor:9092']
#   - job_name: 'redis'
#     static_configs:
#       - targets: ['redis-exporter:9121']
#   - job_name: 'postgres'
#     static_configs:
#       - targets: ['postgres-exporter:9187']
#   - job_name: 'django'
#     static_configs:
#       - targets: ['backend:8000']

global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    metrics_path: '/metrics'
    scheme: 'http'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']