global:
  resolve_timeout: 2m

route:
  receiver: "email-notifications"
  group_by: ["alertname"]
  group_wait: 20s
  group_interval: 3m
  repeat_interval: 30m

receivers:
  - name: "email-notifications"
    email_configs:
      - to: "SMTP_TO"
        from: "SMTP_FROM"
        smarthost: "SMTP_SMARTHOST"
        auth_username: "SMTP_AUTH_USERNAME"
        auth_identity: "SMTP_AUTH_IDENTITY"
        auth_password: "SMTP_AUTH_PASSWORD"
        send_resolved: true
